micronaut:
  application:
    name: chunkerApplication
  server:
    port: ${MICRONAUT_SERVER_PORT:8080}
    host: ${MICRONAUT_SERVER_HOST:localhost}

grpc:
  server:
    port: ${GRPC_SERVER_PORT:50051}
    host: ${GRPC_SERVER_HOST:0.0.0.0}
    enable-reflection: true
