micronaut:
  application:
    name: embedder
  server:
    port: -1  # Disable HTTP server for module
    
grpc:
  server:
    port: 50054  # Following the increment pattern
    health:
      enabled: true

# Module doesn't need Consul or Kafka configuration
# It's just a simple gRPC service

# Embedder-specific configuration
embedder:
  model-type: ${EMBEDDER_MODEL:all-MiniLM-L6-v2}
  max-batch-size: ${EMBEDDER_BATCH_SIZE:32}
  device: ${EMBEDDER_DEVICE:cpu}
  cache-enabled: ${EMBEDDER_CACHE_ENABLED:true}
  cache-size: ${EMBEDDER_CACHE_SIZE:10000}

# Logging
logger:
  levels:
    com.krickert.yappy.modules.embedder: DEBUG