micronaut:
  application:
    name: embedder
  server:
    port: 50051
  metrics:
    enabled: true
  http:
    client:
      read-timeout: 60s
  grpc:
    server:
      port: 50051
      keep-alive-time: 3h
      max-inbound-message-size: 20971520 # 20MB
      health:
        enabled: true
    services:
      embedder:
        enabled: true

# Configure the vectorizers
# Each vectorizer will be created as a bean with the specified configuration
vectorizer:
  default:
    model: ALL_MINILM_L6_V2
    pool-size: 4
    query-prefix: "query: "
    document-prefix: "passage: "
  multilingual:
    model: PARAPHRASE_MULTILINGUAL_MINILM_L12_V2
    pool-size: 2
    query-prefix: "query: "
    document-prefix: "passage: "

# Logging configuration
logger:
  levels:
    com.krickert.yappy.modules.embedder: INFO
    io.micronaut: INFO
