micronaut:
  application:
    name: ${YAPPY_ENGINE_NAME:yappy-engine-tika-parser}
  server:
    port: 8080
  environments: docker
  config-client:
    enabled: ${MICRONAUT_CONFIG_CLIENT_ENABLED:false}

grpc:
  server:
    port: 50051
    health:
      enabled: true
  client:
    plaintext: true

# Application configuration
app:
  config:
    cluster-name: ${YAPPY_CLUSTER_NAME:default-cluster}
    consul:
      key-prefixes:
        pipeline-clusters: "config/pipeline/clusters"
        schema-versions: "config/pipeline/schemas"
        whitelists: "config/pipeline/whitelists"
  engine:
    instance-id: ${HOSTNAME:${random.uuid}}
    bootstrapper:
      enabled: ${YAPPY_BOOTSTRAPPER_ENABLED:false}

# Local service discovery - engine will find Tika Parser on localhost
local:
  services:
    ports:
      tika-parser: 50053

# Health check configuration for local module
health-check:
  tika-parser:
    initial-delay: 5s
    max-attempts: 20
    intervals:
      - 5s    # First 5 attempts (25s total)
      - 10s   # Next 5 attempts (50s total)  
      - 30s   # Next 5 attempts (150s total)
      - 60s   # Next 5 attempts (300s total)
      - 300s  # Every 5 minutes thereafter

# Consul configuration
consul:
  client:
    enabled: ${CONSUL_ENABLED:true}
    host: ${CONSUL_HOST}
    port: ${CONSUL_PORT}
    registration:
      enabled: ${CONSUL_REGISTRATION_ENABLED:true}
      health-check-interval: 10s
      health-check-timeout: 5s
      deregister-critical-service-after: 30s
    config:
      enabled: ${CONSUL_CONFIG_ENABLED:false}
      key:
        prefix: ${CONSUL_CONFIG_KEY_PREFIX:/test/config}
  failFast: false

# Consul key prefixes for pipeline configuration are defined in the app.config.consul.key-prefixes section above

# Kafka configuration
kafka:
  enabled: ${KAFKA_ENABLED:true}
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  schema:
    registry:
      type: ${SCHEMA_REGISTRY_TYPE:apicurio}
  producers:
    pipestream-forwarder:
      key.serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value.serializer: io.apicurio.registry.serde.protobuf.ProtobufKafkaSerializer
      apicurio.registry.url: ${APICURIO_REGISTRY_URL:http://localhost:8080}
      apicurio.registry.auto-register: true
      apicurio.registry.artifact-resolver-strategy: io.apicurio.registry.serde.strategy.TopicIdStrategy

apicurio:
  registry:
    url: ${APICURIO_REGISTRY_URL:http://localhost:8080}

# Logging
logger:
  levels:
    com.krickert: DEBUG
    com.krickert.search.pipeline.engine: DEBUG
    com.krickert.search.config.consul: TRACE
    io.micronaut.discovery: DEBUG
    io.micronaut.health: DEBUG
    io.micronaut.consul: TRACE
    org.kiwiproject.consul: TRACE
