micronaut:
  application:
    name: tika-parser
  server:
    port: -1  # Disable HTTP server for module
    
grpc:
  server:
    port: 50053  # Standard port for Tika Parser
    health:
      enabled: true

# Module doesn't need Consul or Kafka configuration
# It's just a simple gRPC service

# Tika parser configuration
tika:
  parser:
    test-data-buffer:
      enabled: false
    max-file-size: ${TIKA_MAX_FILE_SIZE:52428800}  # 50MB default
    timeout-ms: ${TIKA_TIMEOUT_MS:60000}  # 60 second timeout
    extract-metadata: ${TIKA_EXTRACT_METADATA:true}
    extract-content: ${TIKA_EXTRACT_CONTENT:true}
    detect-language: ${TIKA_DETECT_LANGUAGE:true}

# Logging
logger:
  levels:
    com.krickert.yappy.modules.tikaparser: DEBUG
    org.apache.tika: INFO