micronaut:
  application:
    name: consul-config-service
  server:
    port: 8080

  # Enable the management endpoints for health checks and refresh
  management:
    endpoints:
      health:
        enabled: true
        details-visible: ANONYMOUS
      refresh:
        enabled: true
        sensitive: false
      swagger-ui:
        enabled: true
        sensitive: false
      openapi:
        enabled: true
        sensitive: false
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/resources/webjars/swagger-ui/4.18.2
        mapping: /swagger-ui/**

# Consul client configuration
consul:
  host: localhost
  port: 8500
  client:
    enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
    config:
      enabled: true
      format: YAML
      path: /config/pipeline
    registration:
      check:
        http: true

# Logging configuration
logger:
  levels:
    com.krickert.search.config.consul: INFO
    io.micronaut.discovery: INFO