micronaut:
  application:
    name: opensearch-sink
  server:
    port: 8080

# Kafka configuration
kafka:
  enabled: true
  schema:
    registry:
      type: apicurio

# Logging configuration
logger:
  levels:
    com.krickert.yappy.modules.opensearchsink: INFO
    io.micronaut.context.condition: INFO