package com.krickert.search.config.schema.registry.model;

import io.micronaut.core.annotation.Introspected;
import io.micronaut.core.annotation.Nullable;
import io.micronaut.serde.annotation.Serdeable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.NonNull;

import java.time.Instant;

/**
 * Represents a specific version of a schema for a given artifact (subject) in the schema registry.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Introspected
@Serdeable
public class SchemaVersionData {

    /**
     * A globally unique identifier for this specific schema string and its version,
     * often generated by the registry (e.g., a hash or a sequential ID).
     * Can be null if the primary identification is by subject + version.
     */
    @Nullable
    private Long globalId;

    /**
     * The subject of the schema artifact this version belongs to.
     * Foreign key to SchemaRegistryArtifact.subject.
     */
    @NonNull
    private String subject;

    /**
     * The version number for this schema content (e.g., 1, 2, 3).
     * This is unique per subject.
     */
    @NonNull
    private Integer version;

    /**
     * The actual schema content as a string (e.g., JSON Schema definition).
     */
    @NonNull
    private String schemaContent;

    /**
     * The type of this schema (redundant if SchemaRegistryArtifact also has it,
     * but can be useful for version-specific details if types could mix, though unlikely for JSON Schema).
     * Kept for completeness, often matches the artifact's schemaType.
     */
    @NonNull
    private SchemaType schemaType = SchemaType.JSON_SCHEMA;

    /**
     * The compatibility level of this schema version with its predecessor for the same subject.
     * This would typically be determined by the schema registry upon registration.
     */
    @Nullable
    private SchemaCompatibility compatibility;

    /**
     * Timestamp of when this specific schema version was registered.
     */
    @NonNull
    private Instant createdAt;

    /**
     * An optional description or changelog notes specific to this version of the schema.
     */
    @Nullable
    private String versionDescription;
}