micronaut:
  metrics:
    export:
      jmx:
        enabled: true
        step: PT1M
      statsd:
        enabled: true
        flavor: datadog
        host: localhost
        port: 8125
        step: PT1M
    enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      openapi-explorer:
        paths: classpath:META-INF/swagger/views/openapi-explorer
        mapping: /openapi-explorer/**
consul.client.registration.enabled: false
