micronaut:
  application:
    name: web-crawler-connector
  server:
    port: 8080


# Web crawler configuration
web:
  crawler:
    kafka:
      enabled: true
      input-topic: web-crawl-requests
      output-topic: web-crawl-results
      group-id: web-crawler-group
      client-id: web-crawler-client
    config:
      user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
      max-depth: 0
      max-pages: 1
      stay-within-domain: true
      follow-redirects: true
      timeout-seconds: 30
      headless: true
      extract-text: true
      extract-html: true
      extract-title: true
      kafka-topic: web-crawl-results
      log-prefix: "[WEB-CRAWLER] "
      ublock-extension-path: "ublock_CJPALHDLNBPAFIAMEJDNHCPHJBKEIAGM_1_54_0_0.crx"

# Logging configuration
logger:
  levels:
    com.krickert.yappy.modules.webcrawlerconnector: INFO
    io.micronaut.context.condition: INFO