micronaut:
  application:
    name: wikipedia-connector
  server:
    port: 8080
  grpc:
    server:
      port: 50051
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**

grpc:
  services:
    wikipedia-connector:
      enabled: true

wikipedia:
  connector:
    kafka:
      enabled: true
      group-id: wikipedia-connector-group
      client-id: wikipedia-connector-client
      input-topic: wikipedia-crawl-requests
      output-topic: wikipedia-crawl-results

kafka:
  bootstrap:
    servers: localhost:9092
  schema:
    registry:
      url: http://localhost:8080/apis/registry/v2
  consumers:
    default:
      key:
        deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value:
        deserializer: io.apicurio.registry.serde.protobuf.ProtobufKafkaDeserializer
  producers:
    default:
      key:
        serializer: org.apache.kafka.common.serialization.StringSerializer
      value:
        serializer: io.apicurio.registry.serde.protobuf.ProtobufKafkaSerializer

logger:
  levels:
    com.krickert.yappy.modules.wikipediaconnector: INFO
    io.micronaut.context.condition: INFO