micrometer:
  observation:
    http:
      server:
        enabled: true
      client:
        enabled: true
micronaut:
  application:
    name: yappy-api
  server:
    port: ${SERVER_PORT:8092}
  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
      jmx:
        enabled: true
        step: PT1M
    enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      openapi-explorer:
        paths: classpath:META-INF/swagger/views/openapi-explorer
        mapping: /openapi-explorer/**
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
consul:
  client:
    host: ${CONSUL_HOST:localhost}
    port: ${CONSUL_PORT:8500}
    registration:
      enabled: true
      name: yappy-api
      tags:
        - api
        - admin
    discovery:
      enabled: true
  config:
    enabled: true
    format: YAML

# MongoDB configuration
mongodb:
  uri: ${MONGODB_URI:`mongodb://localhost:27017/yappy`}

# GraphQL configuration
graphql:
  enabled: true
  path: /graphql
  graphiql:
    enabled: true
    path: /graphiql

# Management endpoints
endpoints:
  all:
    enabled: true
    sensitive: false

# OpenAPI configuration
openapi:
  info:
    title: YAPPY Admin API
    version: 1.0.0
    description: REST API for managing YAPPY pipelines and clusters
