kafka:
  enabled: true
  producers:
    pipestream-forwarder: # Matches the id in @KafkaClient
      # bootstrap.servers: localhost:9092 # Or your Kafka brokers
      acks: all  # Wait for all in-sync replicas to acknowledge (highest durability)
      retries: 3 # Number of times the producer will retry sending a message on failure
      # delivery.timeout.ms: 120000 # Max time to wait for ack (includes retries), default 2 mins
      # linger.ms: 5 # Batches records for 5ms to improve throughput under load
      # enable.idempotence: true # Ensures exactly-once semantics per partition (requires acks=all, retries>0, max.in.flight.requests.per.connection<=5)
      # max.in.flight.requests.per.connection: 5 # If idempotence is enabled
      # You can add other standard Kafka producer properties here
      # Example: compression.type: snappy

